### ISSUE TITLE
./install.sh not working

### ISSUE THREAD

**Issue by mattclifford1** [phoenix104104/fast_blind_video_consistency#14]
Error traceback in install.sh

`
Compiling correlation kernels by nvcc...
rm: cannot remove 'correlation_cuda_kernel.o': No such file or directory
./make.sh: line 11: nvcc: command not found
x86_64-linux-gnu-gcc: error: /home/nulightai/Documents/fast_blind_video_consistency/networks/correlation_package/src/correlation_cuda_kernel.o: No such file or directory
Traceback (most recent call last):
  File "/usr/lib/python3.6/distutils/unixccompiler.py", line 207, in link
    self.spawn(linker + ld_args)
  File "/usr/lib/python3.6/distutils/ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/usr/lib/python3.6/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/usr/lib/python3.6/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command 'x86_64-linux-gnu-gcc' failed with exit status 1
`

**Comment by Ssakura-go** [comment]
> Compiling correlation kernels by nvcc... rm: cannot remove 'correlation_cuda_kernel.o': No such file or directory rm: cannot remove '../_ext': No such file or directory nvcc fatal : Path to libdevice library not specified _correlation.c:22:12: fatal error: pyconfig.h: No such file or directory
> 
> # include <pyconfig.h>
> ```
>         ^~~~~~~~~~~~
> ```
> 
> compilation terminated. Traceback (most recent call last): File "/usr/lib/python3.7/distutils/unixccompiler.py", line 118, in _compile extra_postargs) File "/usr/lib/python3.7/distutils/ccompiler.py", line 909, in spawn spawn(cmd, dry_run=self.dry_run) File "/usr/lib/python3.7/distutils/spawn.py", line 36, in spawn _spawn_posix(cmd, search_path, dry_run=dry_run) File "/usr/lib/python3.7/distutils/spawn.py", line 159, in _spawn_posix % (cmd, exit_status)) distutils.errors.DistutilsExecError: command 'x86_64-linux-gnu-gcc' failed with exit status 1
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/home/nulightai/.local/lib/python3.7/site-packages/cffi/ffiplatform.py", line 51, in _build dist.run_command('build_ext') File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command cmd_obj.run() File "/usr/lib/python3.7/distutils/command/build_ext.py", line 340, in run self.build_extensions() File "/usr/lib/python3.7/distutils/command/build_ext.py", line 449, in build_extensions self._build_extensions_serial() File "/usr/lib/python3.7/distutils/command/build_ext.py", line 474, in _build_extensions_serial self.build_extension(ext) File "/usr/lib/python3.7/distutils/command/build_ext.py", line 534, in build_extension depends=ext.depends) File "/usr/lib/python3.7/distutils/ccompiler.py", line 574, in compile self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts) File "/usr/lib/python3.7/distutils/unixccompiler.py", line 120, in _compile raise CompileError(msg) distutils.errors.CompileError: command 'x86_64-linux-gnu-gcc' failed with exit status 1
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "build.py", line 31, in ffi.build() File "/home/nulightai/.local/lib/python3.7/site-packages/torch/utils/ffi/**init**.py", line 189, in build _build_extension(ffi, cffi_wrapper_name, target_dir, verbose) File "/home/nulightai/.local/lib/python3.7/site-packages/torch/utils/ffi/**init**.py", line 111, in _build_extension outfile = ffi.compile(tmpdir=tmpdir, verbose=verbose, target=libname) File "/home/nulightai/.local/lib/python3.7/site-packages/cffi/api.py", line 723, in compile compiler_verbose=verbose, debug=debug, **kwds) File "/home/nulightai/.local/lib/python3.7/site-packages/cffi/recompiler.py", line 1526, in recompile compiler_verbose, debug) File "/home/nulightai/.local/lib/python3.7/site-packages/cffi/ffiplatform.py", line 22, in compile outputfilename = _build(tmpdir, ext, compiler_verbose, debug) File "/home/nulightai/.local/lib/python3.7/site-packages/cffi/ffiplatform.py", line 58, in _build raise VerificationError('%s: %s' % (e.**class**.**name**, e)) cffi.VerificationError: CompileError: command 'x86_64-linux-gnu-gcc' failed with exit status 1

Did you have solved this problem? I met the same issue as you met before.
